export const RECEIVE_RECHARGE_SUBSCRIPTION_ITEMS = 'RECEIVE_RECHARGE_SUBSCRIPTION_ITEMS';
export const REQUEST_RECHARGE_SUBSCRIPTION_ITEMS = 'REQUEST_RECHARGE_SUBSCRIPTION_ITEMS';
export const ERROR_RECHARGE_SUBSCRIPTION_ITEMS = 'ERROR_RECHARGE_SUBSCRIPTION_ITEMS';

export const REDUX_NAMESPACE_RECHARGE_SUBSCRIPTION_ITEMS = '@shopgate-project//recharge/rechargeSubscriptionItems';
